#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* nlpapiv2
* The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMHateSpeechAnalysisResponse
@end

@interface CMHateSpeechAnalysisResponse : CMObject

/* True if the profanity detection operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Hate speech classification score between 0.0 and 1.0 where scores closer to zero have a low probability of being hate speech language, while scores close to 1.0 have a high probability of being hate speech language.  Values above 0.8 have a very high probability of being hate speech. [optional]
 */
@property(nonatomic) NSNumber* hateSpeechScoreResult;
/* Number of sentences in input text [optional]
 */
@property(nonatomic) NSNumber* sentenceCount;

@end
