#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* nlpapiv2
* The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMRephrasedSentenceOption
@end

@interface CMRephrasedSentenceOption : CMObject

/* Ordered index of the rephrasing option, 1-based, with 1 being the best option [optional]
 */
@property(nonatomic) NSNumber* rephrasedOptionIndex;
/* One sentence of output rephrased text of original input sentence [optional]
 */
@property(nonatomic) NSString* rephrasedSentenceText;

@end
