#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* nlpapiv2
* The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMSentimentAnalysisResponse
@end

@interface CMSentimentAnalysisResponse : CMObject

/* True if the sentiment analysis operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Classification of input text into a sentiment classification; possible values are \"Positive\", \"Negative\" or \"Neutral\" [optional]
 */
@property(nonatomic) NSString* sentimentClassificationResult;
/* Sentiment classification score between -1.0 and +1.0 where scores less than 0 are negative sentiment, scores greater than 0 are positive sentiment and scores close to 0 are neutral.  The greater the value deviates from 0.0 the stronger the sentiment, with +1.0 and -1.0 being maximum positive and negative sentiment, respectively. [optional]
 */
@property(nonatomic) NSNumber* sentimentScoreResult;
/* Number of sentences in input text [optional]
 */
@property(nonatomic) NSNumber* sentenceCount;

@end
