#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* nlpapiv2
* The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMSimilarityAnalysisResponse
@end

@interface CMSimilarityAnalysisResponse : CMObject

/* True if the similarity analysis operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Similarity score between 0.0 and 1.0 where scores closer to zero have a low probability of semantic similarity, while scores close to 1.0 have a high probability of semantic similarity. [optional]
 */
@property(nonatomic) NSNumber* similarityScoreResult;
/* Number of sentences in input text [optional]
 */
@property(nonatomic) NSNumber* sentenceCount;

@end
