#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* nlpapiv2
* The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMSubjectivityAnalysisResponse
@end

@interface CMSubjectivityAnalysisResponse : CMObject

/* True if the subjectivity analysis operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Subjectivity vs. objectivity classification score between 0.0 and 1.0 where scores closer to zero have a high probability of objectivity, while scores close to 1.0 have a high probability of subjectivity. [optional]
 */
@property(nonatomic) NSNumber* subjectivityScoreResult;
/* Number of sentences in input text [optional]
 */
@property(nonatomic) NSNumber* sentenceCount;

@end
