#import <Foundation/Foundation.h>
#import "CMExtractEntitiesRequest.h"
#import "CMExtractEntitiesResponse.h"
#import "CMApi.h"

/**
* nlpapiv2
* The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMExtractEntitiesApi: NSObject <CMApi>

extern NSString* kCMExtractEntitiesApiErrorDomain;
extern NSInteger kCMExtractEntitiesApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Extract entities from string
/// Extract the named entitites from an input string.
///
/// @param value Input string
/// 
///  code:200 message:"OK"
///
/// @return CMExtractEntitiesResponse*
-(NSURLSessionTask*) extractEntitiesPostWithValue: (CMExtractEntitiesRequest*) value
    completionHandler: (void (^)(CMExtractEntitiesResponse* output, NSError* error)) handler;



@end
