#import <Foundation/Foundation.h>
#import "CMLanguageDetectionResponse.h"
#import "CMApi.h"

/**
* nlpapi
* The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMLanguageDetectionApi: NSObject <CMApi>

extern NSString* kCMLanguageDetectionApiErrorDomain;
extern NSInteger kCMLanguageDetectionApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Detect language of text
/// Automatically determine which language a text string is written in.  Supports Danish (DAN), German (DEU), English (ENG), French (FRA), Italian (ITA), Japanese (JPN), Korean (KOR), Dutch (NLD), Norwegian (NOR), Portuguese (POR), Russian (RUS), Spanish (SPA), Swedish (SWE), Chinese (ZHO).
///
/// @param textToDetect Text to detect language of
/// 
///  code:200 message:"OK"
///
/// @return CMLanguageDetectionResponse*
-(NSURLSessionTask*) languageDetectionPostWithTextToDetect: (NSString*) textToDetect
    completionHandler: (void (^)(CMLanguageDetectionResponse* output, NSError* error)) handler;



@end
