#import <Foundation/Foundation.h>
#import "CMLanguageTranslationRequest.h"
#import "CMLanguageTranslationResponse.h"
#import "CMApi.h"

/**
* nlpapiv2
* The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMLanguageTranslationApi: NSObject <CMApi>

extern NSString* kCMLanguageTranslationApiErrorDomain;
extern NSInteger kCMLanguageTranslationApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Translate German to English text with Deep Learning AI
/// Automatically translates input text in German to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
///
/// @param input Input translation request
/// 
///  code:200 message:"OK"
///
/// @return CMLanguageTranslationResponse*
-(NSURLSessionTask*) languageTranslationTranslateDeuToEngWithInput: (CMLanguageTranslationRequest*) input
    completionHandler: (void (^)(CMLanguageTranslationResponse* output, NSError* error)) handler;


/// Translate English to German text with Deep Learning AI
/// Automatically translates input text in English to output text in German using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
///
/// @param input Input translation request
/// 
///  code:200 message:"OK"
///
/// @return CMLanguageTranslationResponse*
-(NSURLSessionTask*) languageTranslationTranslateEngToDeuWithInput: (CMLanguageTranslationRequest*) input
    completionHandler: (void (^)(CMLanguageTranslationResponse* output, NSError* error)) handler;


/// Translate English to French text with Deep Learning AI
/// Automatically translates input text in English to output text in French using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
///
/// @param input Input translation request
/// 
///  code:200 message:"OK"
///
/// @return CMLanguageTranslationResponse*
-(NSURLSessionTask*) languageTranslationTranslateEngToFraWithInput: (CMLanguageTranslationRequest*) input
    completionHandler: (void (^)(CMLanguageTranslationResponse* output, NSError* error)) handler;


/// Translate English to Russian text with Deep Learning AI
/// Automatically translates input text in English to output text in Russian using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
///
/// @param input Input translation request
/// 
///  code:200 message:"OK"
///
/// @return CMLanguageTranslationResponse*
-(NSURLSessionTask*) languageTranslationTranslateEngToRusWithInput: (CMLanguageTranslationRequest*) input
    completionHandler: (void (^)(CMLanguageTranslationResponse* output, NSError* error)) handler;


/// Translate French to English text with Deep Learning AI
/// Automatically translates input text in French to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
///
/// @param input Input translation request
/// 
///  code:200 message:"OK"
///
/// @return CMLanguageTranslationResponse*
-(NSURLSessionTask*) languageTranslationTranslateFraToEngWithInput: (CMLanguageTranslationRequest*) input
    completionHandler: (void (^)(CMLanguageTranslationResponse* output, NSError* error)) handler;


/// Translate Russian to English text with Deep Learning AI
/// Automatically translates input text in Russian to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
///
/// @param input Input translation request
/// 
///  code:200 message:"OK"
///
/// @return CMLanguageTranslationResponse*
-(NSURLSessionTask*) languageTranslationTranslateRusToEngWithInput: (CMLanguageTranslationRequest*) input
    completionHandler: (void (^)(CMLanguageTranslationResponse* output, NSError* error)) handler;



@end
