#import <Foundation/Foundation.h>
#import "CMApi.h"

/**
* nlpapi
* The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMParseStringApi: NSObject <CMApi>

extern NSString* kCMParseStringApiErrorDomain;
extern NSInteger kCMParseStringApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Parse string to syntax tree
/// Parses the input string into a Penn Treebank syntax tree
///
/// @param input Input string
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) parseStringPostWithInput: (NSString*) input
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;



@end
