#import <Foundation/Foundation.h>
#import "CMParseRequest.h"
#import "CMParseResponse.h"
#import "CMApi.h"

/**
* nlpapiv2
* The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMParseApi: NSObject <CMApi>

extern NSString* kCMParseApiErrorDomain;
extern NSInteger kCMParseApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Parse string to syntax tree
/// Parses the input string into a Penn Treebank syntax tree
///
/// @param input Input string
/// 
///  code:200 message:"OK"
///
/// @return CMParseResponse*
-(NSURLSessionTask*) parseParseStringWithInput: (CMParseRequest*) input
    completionHandler: (void (^)(CMParseResponse* output, NSError* error)) handler;



@end
