#import <Foundation/Foundation.h>
#import "CMPosRequest.h"
#import "CMPosResponse.h"
#import "CMApi.h"

/**
* nlpapi
* The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMPosTaggerJsonApi: NSObject <CMApi>

extern NSString* kCMPosTaggerJsonApiErrorDomain;
extern NSInteger kCMPosTaggerJsonApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Part-of-speech tag a string
/// Part-of-speech (POS) tag a string and return result as JSON
///
/// @param request Input string
/// 
///  code:200 message:"OK"
///
/// @return CMPosResponse*
-(NSURLSessionTask*) posTaggerJsonPostWithRequest: (CMPosRequest*) request
    completionHandler: (void (^)(CMPosResponse* output, NSError* error)) handler;



@end
