#import <Foundation/Foundation.h>
#import "CMApi.h"

/**
* nlpapi
* The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMPosTaggerStringApi: NSObject <CMApi>

extern NSString* kCMPosTaggerStringApiErrorDomain;
extern NSInteger kCMPosTaggerStringApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Part-of-speech tag a string
/// Perform a part-of-speech (POS) tagging on the input string.
///
/// @param input Input string
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) posTaggerStringPostWithInput: (NSString*) input
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;



@end
