#import <Foundation/Foundation.h>
#import "CMPosRequest.h"
#import "CMPosResponse.h"
#import "CMApi.h"

/**
* nlpapiv2
* The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMPosTaggerApi: NSObject <CMApi>

extern NSString* kCMPosTaggerApiErrorDomain;
extern NSInteger kCMPosTaggerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Part-of-speech tag a string, filter to adjectives
/// Part-of-speech (POS) tag a string, find the adjectives, and return result as JSON
///
/// @param request Input string
/// 
///  code:200 message:"OK"
///
/// @return CMPosResponse*
-(NSURLSessionTask*) posTaggerTagAdjectivesWithRequest: (CMPosRequest*) request
    completionHandler: (void (^)(CMPosResponse* output, NSError* error)) handler;


/// Part-of-speech tag a string, filter to adverbs
/// Part-of-speech (POS) tag a string, find the adverbs, and return result as JSON
///
/// @param request Input string
/// 
///  code:200 message:"OK"
///
/// @return CMPosResponse*
-(NSURLSessionTask*) posTaggerTagAdverbsWithRequest: (CMPosRequest*) request
    completionHandler: (void (^)(CMPosResponse* output, NSError* error)) handler;


/// Part-of-speech tag a string, filter to nouns
/// Part-of-speech (POS) tag a string, find the nouns, and return result as JSON
///
/// @param request Input string
/// 
///  code:200 message:"OK"
///
/// @return CMPosResponse*
-(NSURLSessionTask*) posTaggerTagNounsWithRequest: (CMPosRequest*) request
    completionHandler: (void (^)(CMPosResponse* output, NSError* error)) handler;


/// Part-of-speech tag a string, filter to pronouns
/// Part-of-speech (POS) tag a string, find the pronouns, and return result as JSON
///
/// @param request Input string
/// 
///  code:200 message:"OK"
///
/// @return CMPosResponse*
-(NSURLSessionTask*) posTaggerTagPronounsWithRequest: (CMPosRequest*) request
    completionHandler: (void (^)(CMPosResponse* output, NSError* error)) handler;


/// Part-of-speech tag a string
/// Part-of-speech (POS) tag a string and return result as JSON
///
/// @param request Input string
/// 
///  code:200 message:"OK"
///
/// @return CMPosResponse*
-(NSURLSessionTask*) posTaggerTagSentenceWithRequest: (CMPosRequest*) request
    completionHandler: (void (^)(CMPosResponse* output, NSError* error)) handler;


/// Part-of-speech tag a string, filter to verbs
/// Part-of-speech (POS) tag a string, find the verbs, and return result as JSON
///
/// @param request Input string
/// 
///  code:200 message:"OK"
///
/// @return CMPosResponse*
-(NSURLSessionTask*) posTaggerTagVerbsWithRequest: (CMPosRequest*) request
    completionHandler: (void (^)(CMPosResponse* output, NSError* error)) handler;



@end
