#import <Foundation/Foundation.h>
#import "CMGetWordsRequest.h"
#import "CMGetWordsResponse.h"
#import "CMSentenceSegmentationRequest.h"
#import "CMSentenceSegmentationResponse.h"
#import "CMApi.h"

/**
* nlpapiv2
* The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMSegmentationApi: NSObject <CMApi>

extern NSString* kCMSegmentationApiErrorDomain;
extern NSInteger kCMSegmentationApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Extract sentences from string
/// Segment an input string into separate sentences, output result as a string.
///
/// @param input Input string
/// 
///  code:200 message:"OK"
///
/// @return CMSentenceSegmentationResponse*
-(NSURLSessionTask*) segmentationGetSentencesWithInput: (CMSentenceSegmentationRequest*) input
    completionHandler: (void (^)(CMSentenceSegmentationResponse* output, NSError* error)) handler;


/// Get words in input string
/// Get the component words in an input string
///
/// @param input String to process
/// 
///  code:200 message:"OK"
///
/// @return CMGetWordsResponse*
-(NSURLSessionTask*) segmentationGetWordsWithInput: (CMGetWordsRequest*) input
    completionHandler: (void (^)(CMGetWordsResponse* output, NSError* error)) handler;



@end
