#import <Foundation/Foundation.h>
#import "CMCheckJsonResponse.h"
#import "CMCheckSentenceJsonResponse.h"
#import "CMCorrectJsonResponse.h"
#import "CMApi.h"

/**
* nlpapi
* The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMSpellCheckApi: NSObject <CMApi>

extern NSString* kCMSpellCheckApiErrorDomain;
extern NSInteger kCMSpellCheckApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Spell check word
/// Spell check a word as JSON
///
/// @param value Input sentence
/// 
///  code:200 message:"OK"
///
/// @return CMCheckJsonResponse*
-(NSURLSessionTask*) spellCheckCheckJsonWithValue: (NSString*) value
    completionHandler: (void (^)(CMCheckJsonResponse* output, NSError* error)) handler;


/// Check if sentence is spelled correctly
/// Checks whether the sentence is spelled correctly and returns the result as JSON
///
/// @param value Input sentence
/// 
///  code:200 message:"OK"
///
/// @return CMCheckSentenceJsonResponse*
-(NSURLSessionTask*) spellCheckCheckSentenceJsonWithValue: (NSString*) value
    completionHandler: (void (^)(CMCheckSentenceJsonResponse* output, NSError* error)) handler;


/// Spell check a sentence
/// Check if a sentence is spelled correctly
///
/// @param value Input sentence word
/// 
///  code:200 message:"OK"
///
/// @return NSNumber*
-(NSURLSessionTask*) spellCheckCheckSentenceStringWithValue: (NSString*) value
    completionHandler: (void (^)(NSNumber* output, NSError* error)) handler;


/// Find spelling corrections
/// Find the spelling corrections for a word
///
/// @param value Input word
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) spellCheckCorrectWithValue: (NSString*) value
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Find spelling corrections
/// Find spelling correction suggestions and return result as JSON
///
/// @param value Input string
/// 
///  code:200 message:"OK"
///
/// @return CMCorrectJsonResponse*
-(NSURLSessionTask*) spellCheckCorrectJsonWithValue: (NSString*) value
    completionHandler: (void (^)(CMCorrectJsonResponse* output, NSError* error)) handler;


/// Spell check a word
/// Check if a word is spelled correctly
///
/// @param value Input string word
/// 
///  code:200 message:"OK"
///
/// @return NSNumber*
-(NSURLSessionTask*) spellCheckPostWithValue: (NSString*) value
    completionHandler: (void (^)(NSNumber* output, NSError* error)) handler;



@end
