#import <Foundation/Foundation.h>
#import "CMCheckSentenceRequest.h"
#import "CMCheckSentenceResponse.h"
#import "CMCheckWordRequest.h"
#import "CMCheckWordResponse.h"
#import "CMApi.h"

/**
* nlpapiv2
* The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMSpellcheckApi: NSObject <CMApi>

extern NSString* kCMSpellcheckApiErrorDomain;
extern NSInteger kCMSpellcheckApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Check if sentence is spelled correctly
/// Checks whether the sentence is spelled correctly and returns the result as JSON
///
/// @param value Input sentence
/// 
///  code:200 message:"OK"
///
/// @return CMCheckSentenceResponse*
-(NSURLSessionTask*) spellcheckCheckSentenceWithValue: (CMCheckSentenceRequest*) value
    completionHandler: (void (^)(CMCheckSentenceResponse* output, NSError* error)) handler;


/// Find spelling corrections
/// Find spelling correction suggestions and return result as JSON
///
/// @param value Input string
/// 
///  code:200 message:"OK"
///
/// @return CMCheckWordResponse*
-(NSURLSessionTask*) spellcheckCorrectJsonWithValue: (CMCheckWordRequest*) value
    completionHandler: (void (^)(CMCheckWordResponse* output, NSError* error)) handler;



@end
