#import <Foundation/Foundation.h>
#import "CMGetWordsJsonResponse.h"
#import "CMApi.h"

/**
* nlpapi
* The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMWordsApi: NSObject <CMApi>

extern NSString* kCMWordsApiErrorDomain;
extern NSInteger kCMWordsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Get adjectives in string
/// Retrieves all adjectives in input string
///
/// @param input Input string
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) wordsAdjectivesWithInput: (NSString*) input
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Get adverbs in input string
/// Returns all adverb words in the input string
///
/// @param input Input string
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) wordsAdverbsWithInput: (NSString*) input
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Get words in input string (JSON)
/// Get the component words in an input string, formatted as JSON
///
/// @param input String to process
/// 
///  code:200 message:"OK"
///
/// @return CMGetWordsJsonResponse*
-(NSURLSessionTask*) wordsGetWordsJsonWithInput: (NSString*) input
    completionHandler: (void (^)(CMGetWordsJsonResponse* output, NSError* error)) handler;


/// Get words from string
/// Segment an input string into its component words
///
/// @param input Input string
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) wordsGetWordsStringWithInput: (NSString*) input
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Get nouns in string
/// Returns all of the nouns in the input string
///
/// @param input Input string
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) wordsNounsWithInput: (NSString*) input
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Get the verbs in a string
/// Get all of the verbs in the input string.
///
/// @param input Input string
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) wordsPostWithInput: (NSString*) input
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Returns all pronounts in string
/// Returns all pronouns in the input string
///
/// @param input Input string
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) wordsPronounsWithInput: (NSString*) input
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Get proper nouns in a string
/// Returns all of the proper nouns in a string.  Proper nouns are named entities such as \"Hilton\".
///
/// @param input Input string
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) wordsProperNounsWithInput: (NSString*) input
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;



@end
